name: Rust

on:
  push:
    branches: [ main, impl ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ITD/backend
    env:
        DATABASE_URL: "postgresql://clup:postgres@localhost/clup_sqlx"
        # REDIS_URL: "127.0.0.1:6379"
        SESSION_KEY: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    steps:
    - uses: actions/checkout@v2
    - name: Database setup # Could be omitted if sqlx-data.json is guaranteed to be updated
      run: | 
        cargo install sqlx-cli
        cargo sqlx prepare -- --lib
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    services:
      postgres: 
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: clup
        ports: 
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
